# CI de Nível 01 - Disparo manual a partir de 1 clique
# nome do nosso 'pipeline'
name: 'Execução Manual'
# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:
# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  unidade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando Testes de Unidade com Mocha
        run: ./node_modules/.bin/mocha rest/testes/testes.js
